### ISSUE TITLE
Documentation redirects to wrong version

### ISSUE THREAD

**Issue by petermarko** [siemens/kas#10]
Clicking on documentation link in README points to wrong page.
* link: https://kas.readthedocs.io/
* redirect: https://kas.readthedocs.io/en/0.19.0/
* expected: https://kas.readthedocs.io/en/1.0/

**Comment by igaw** [comment]
Thanks for the report. Should be fixed now.

Unfortunately, everytime we do a release someone (me) has to remember to do this. I haven't figured out how to get readthedocs to update it automatically...
