### ISSUE TITLE
.netrc should not contain comments

### ISSUE THREAD

**Issue by adamjohnstonarm** [siemens/kas#111]
A recent [change](https://github.com/openembedded/openembedded-core/commit/ba391d39f2b888706e53028e9df3a37c5baedfc1) to OE core causes bitbake to fallback to netrc when
BB_HASHSERVE_USERNAME or BB_HASHSERVE_PASSWORD are not set.

This exposes us to an error when running in GitLab because kas has been
inserting a comment into ~/.netrc.

`# appended by kas, you have gitlab CI env`

Resulting in...

`netrc.NetrcParseError: bad toplevel token 'appended'`

The comment should not be added is it relies on undocumented behaviour.

**Comment by adamjohnstonarm** [comment]
Fix sent to mailing list

**Comment by adamjohnstonarm** [comment]
See #112

**Comment by jonmason** [comment]
Can we get this in a tagged release, as we're having to carry a patch in our CI to work around it?  Perhaps 4.3.2.

**Comment by jan-kiszka** [comment]
Working towards this, should appear this week.

**Comment by fmoessbauer** [comment]
We now have the 4.3.2 release, which includes the fix. By that, we can close this issue. @jan-kiszka
