### ISSUE TITLE
dump --resolve-refs fails when using name

### ISSUE THREAD

**Issue by kwavnet** [siemens/kas#131]
running `kas dump --resolve-refs` with

```
header:
  version: 14
repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    tag: kirkstone-4.0.20
    name: foo
    path: sources/poky
    layers:
      meta:
```

fails with

```
Traceback (most recent call last):
  File "/.env/lib/python3.10/site-packages/kas/kas.py", line 205, in main
    kas(sys.argv[1:])
  File "/.env/lib/python3.10/site-packages/kas/kas.py", line 194, in kas
    plugin.run(args)
  File "/.env/lib/python3.10/site-packages/kas/plugins/dump.py", line 225, in run
    config_expanded['repos'][r.name]['commit'] = r.revision
KeyError: 'foo'
```

the same call without the `name` in the config

```
header:
  version: 14
repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    tag: kirkstone-4.0.20
    path: sources/poky
    layers:
      meta:
```

works absolutely fine.
Reproduceable on 4.x releases and the next branch

**Comment by jan-kiszka** [comment]
@fmoessbauer

**Comment by fmoessbauer** [comment]
@kwavnet Thanks for reporting. This should easily be fixable. I'll send a patch to the ML by today. If you like I can give you credit in a `Reported-by` tag.

**Comment by kwavnet** [comment]
> @kwavnet Thanks for reporting. This should easily be fixable. I'll send a patch to the ML by today. If you like I can give you credit in a `Reported-by` tag.

@fmoessbauer 😊 not needed, I was just stumbling upon that issue (functionality isn't mission critical for me), so I thought better to report - so as long as a fix lands in master at any point I'm good
