### ISSUE TITLE
/usr/local/bin/ not exposed in PATH

### ISSUE THREAD

**Issue by kwavnet** [siemens/kas#132]
In my custom container I have a tool installed under `/usr/local/bin/` but that isn't exposed in the standard environment when running `kas shell -c something`.

See https://github.com/siemens/kas/blob/80636528e6d5b9bfd78a4d70eeb2fa6a56fcc6c8/kas/libkas.py#L267

Wouldn't it make sense to expose that as well?
At least on my Ubuntu 20.04+ based containers a lot of tools end up in this folder

**Comment by jan-kiszka** [comment]
Try `kas shell --preserve-env` for that special case.

For the generic case, we intentionally not expose local paths like that to remind users when they try to create some non-portable config this way.
