### ISSUE TITLE
kas-docker does not seem to work when binfmt misc uses different configuration on host

### ISSUE THREAD

**Issue by cgerum** [siemens/kas#19]
When trying to run kas-docker I got the following error message:

```
| I: Running command: chroot /work/build/tmp/work/jailhouse-demo-arm64/isar-bootstrap-target/1.0-r0/rootfs /debootstrap/debootstrap --second-stage
| chroot: failed to run command ‘/debootstrap/debootstrap’: No such file or directory
| WARNING: exit code 127 from a shell command.
| 
ERROR: Task (mc:qemu-arm64-jailhouse-demo:/work/isar/meta/recipes-core/isar-bootstrap/isar-bootstrap-target.bb:do_bootstrap) failed with exit code '1'
```
The cause of the error was not that debootstrap/debootstrap was actually missing, but that /proc/sys/fs/binfmt_misc/qemu-aarch64 contained the wrong path to the qemu-interpreter. Due to a different binfmt-support setup on the host. 

I don't know wether this is actually solvable in kas-docker, but at least this ticket might help somone to find the cause of the error.

**Comment by henning-schild** [comment]
In general we do not do issues, you should use the mailing list for questions, bug reports and patches.

You should try https://github.com/siemens/jailhouse-images and see if that works for you. My first guess is that you did not run `kas-docker` with `--isar`, which is required to set up binfmt and choose the right container with everything you need for an isar build.
