### ISSUE TITLE
Loose dependencies cause forward compatibility issues

### ISSUE THREAD

**Issue by denravonska** [siemens/kas#34]
Looking at `setup.py` it seems like the dependencies are only specified using a lower limit, something which is bound to cause reproducibility issues in the future:

```
install_requires=[
        'PyYAML>=3.0',
        'distro>=1.0.0',
        'jsonschema>=2.5.0',
    ],
```

When you install a certain kas version you never know if it's going to be compatible with its dependencies, something it will inevitably not be as time goes on. This should be changed to a reasonable upper bound which depends on how the dependencies manage their versions.

**Comment by jan-kiszka** [comment]
Thanks for the report, need to look into this before the next release. I'm not familiar enough with the components to quickly tell which version series to choose for each of them.
