### ISSUE TITLE
Support the runqemu command

### ISSUE THREAD

**Issue by deinok** [siemens/kas#4]

**Comment by jan-kiszka** [comment]
Please describe in more details the additional use case you see, and ideally do this on the mailing list (kas-devel@googlegroups.com).

**Comment by deinok** [comment]
Like the build plugin more or less wraps the bitbake command, create a plugin to wrap the runqemu command.

Ex:
`kas runqemu kas.yml` ensures that the build is updated an then it bootstrap the qemu with the image generated from the build.

**Comment by jan-kiszka** [comment]
What would be the added value to something like `kas shell -c runqemu kas.yml`?

**Comment by deinok** [comment]
Didn't know that this can be done.
It would be great to have a bit more documentation with this kind of things :)
