### ISSUE TITLE
kas-container usage

### ISSUE THREAD

**Issue by coschneider** [siemens/kas#42]
Hi,

thanks for your great work.

When I try to run the following command I get an error :
```bash
$ KAS_WORK_DIR=$PWD/tmp-build/ DL_DIR=$PWD/downloads ./kas-container shell test.yml -c "bitbake package-index"
usage: kas [-h] [--version] [-d] {build,checkout,for-all-repos,shell} ...
kas: error: unrecognized arguments: /repo/test.yml
```

How can I call a shell bitbake command with the docker container solution? With plain kas command it works as expected.

**Comment by jan-kiszka** [comment]
Please try out https://groups.google.com/g/kas-devel/c/E3mv6OCN_X8 and give feedback if that works.

**Comment by coschneider** [comment]
Now it works like a charm. Thanks a lot for your quick fix/patch.
