### ISSUE TITLE
Docker image version is out-of-date

### ISSUE THREAD

**Issue by vivien** [siemens/kas#48]
Kas latest release is 2.3.3 but the latest Docker image is 2.2. Can a 2.3.3 docker image be published?

**Comment by jan-kiszka** [comment]
In fact, latest is 2.4.

You likely still look at old dockerhub, but we migrated here, to ghcr.io. See https://kas.readthedocs.io/en/latest/userguide.html#usage.

**Comment by vivien** [comment]
Nope, this [Usage](https://kas.readthedocs.io/en/latest/userguide.html#usage) documentation provides a [link](https://github.com/orgs/siemens/packages/container/kas%2Fkas/31765) only mentioning kas:2.2.

**Comment by jan-kiszka** [comment]
Ah, indeed, thanks! We need to patch in some better link, maybe https://github.com/orgs/siemens/packages/container/kas%2Fkas/versions. Let me check...
