### ISSUE TITLE
DL_DIR in local_conf_header doesn't work anymore with kas-container 2.5

### ISSUE THREAD

**Issue by vivien** [siemens/kas#52]
`PermissionError: [Errno 13] Permission denied: '/downloads'`

**Comment by vivien** [comment]
It looks like since 2.5, the repo is mounted read-only by default for `build`, hence the permission denied. The problem is that some configuration like these could be added in `local_conf_header` before. Using the `DL_DIR` environment variable works.

**Comment by jan-kiszka** [comment]
Works for me, though - can you provide more details on how to reproduce?

**Comment by jan-kiszka** [comment]
Ah, local_conf_header... that may explain why some random DL_DIR may not be writeable if it is under repo, but not repo/build. But I do not see yet why this should have worked before - likely - 06240c23da6e8fc23146cf8e6814efbd5a08e5d7.

**Comment by vivien** [comment]
with `kas-container build` the repo is mounted read-only. If the *DL_DIR* is stated inside the *local_conf_header*, the script does not explicitly know about it (as opposed to passing *DL_DIR* via the environment which adds a rw volume) and thus the directory (`${TOPDIR}/../downloads` in my case) ends up being read-only.

**Comment by jan-kiszka** [comment]
Yes, but it was mounted read-only before as well. So, the situation you describe is real, but not new. And I'm also not sure if we can resolve it automatically without more and more logic in that "simple" kas-container script.

If your project chooses a location that is output of `build` - or even absolute and outside of `repo` -, it's on its own ground. For anything inside of `repo`, you can at least help out and provide `--repo-rw`. But how should kas-container know that upfront?

**Comment by vivien** [comment]
I agree, assuming that `repo` is mounted read-only is a good idea, it's a layer after all. I'm just pointing out that I was using `DL_DIR = "${TOPDIR}/../downloads" with 2.4, which now doesn't work with 2.5. I'm fine with this being deprecated if that is explicitely stated somewhere in the doc.

**Comment by jan-kiszka** [comment]
As I pointed out, this is no change in behaviour. Already 2.4 rejected
```
local_conf_header:
  dldir: |
    DL_DIR: "${TOPDIR}/../downloads"
```
Just tested and confirmed that.

**Comment by vivien** [comment]
Very strange that it worked for me until 2.5! Anyway, the point is that *DL_DIR* in *local_conf_header* is not kas-friendly, now it's clear.
