### ISSUE TITLE
Devtool config clobbered when leaving and re-entering `kas shell`

### ISSUE THREAD

**Issue by willstott101** [siemens/kas#58]
devtool modifies the local layers/config to add a layer which overwrites specific recipe sources to local checkouts. This is massively useful when developing code to run within a yocto-built environment. But re-entering the kas shell overwrites the config changes that devtool made. It'd be great if kas could do something to integrate with devtool more seamlessly

**Comment by willstott101** [comment]
Ah re-running `devtool modify` worked to reinstate it.

**Comment by jan-kiszka** [comment]
Also note that there is `--keep-config-unchanged` on the kas side.
