### ISSUE TITLE
Need a manpage for kas command

### ISSUE THREAD

**Issue by winndows** [siemens/kas#74]
It is better to have a manpage for kas command.

Thanks.

**Comment by jan-kiszka** [comment]
Happy to take patches that convert existing docs into a man page, possibly enhancing it along that.

**Comment by JosephMillsAtWork** [comment]
If I change directory to docs and run 

make man

It seems to work very well.  I guess this would be a distro deal at that point for install.

**Comment by jan-kiszka** [comment]
Ah, indeed, didn't know that myself. There are many formats available, in fact. And Debian does use this (https://packages.debian.org/bookworm/all/kas/filelist).
