### ISSUE TITLE
sstate_cache support

### ISSUE THREAD

**Issue by yli147** [siemens/kas#83]
Hi,

I'm using 
KAS_CONTAINER_IMAGE=ghcr.io/siemens/kas/kas-isar:3.1 and ./kas-container to cross compile my image. But there is no sstate_cache folder generated.  Even I explicted declare the SSTATE_DIR marco , there is still no shared cache generated. Any idea ?

**Comment by jan-kiszka** [comment]
Unless you tweak `KAS_WORK_DIR`, you will find `build/sstate-cache` in the current workdir, ottherwise under `${KAS_WORK_DIR}/sstate-cache`. `SSTATE_DIR` inside the build container is managed by kas as needed.

**Comment by yli147** [comment]
No. only below files/folders under build folder
bitbake-cookerdaemon.log  conf  downloads  tmp

**Comment by yli147** [comment]
I'm using this project https://github.com/siemens/isar-riscv

**Comment by jan-kiszka** [comment]
That project is using an Isar revision pre-dating sstate support.

**Comment by yli147** [comment]
Then, how to upgrade the isar to support the sstate, thanks !

**Comment by jan-kiszka** [comment]
Raise a PR with isar-riscv, bumping the Isar revision in the related kas config file and likely also updating the recipes to make that new version work. But it's not a kas issue.

**Comment by yli147** [comment]
Thanks for the information, will try.

**Comment by jan-kiszka** [comment]
Closing as not being a kas topic.
