### ISSUE TITLE
Error handling in shell script

### ISSUE THREAD

**Issue by tewarid** [siemens/kas#85]
I want to run some commands after a successful kas build, hence my shell script looks like

```bash
kas build ...
if [ $? -eq 0 ]; then
...
```

Even though kas build fails, the commands still run.

Am I missing something?

**Comment by jan-kiszka** [comment]
I cannot confirm this, e.g. by calling `kas build config.yaml --target invalid`. `$?` is non-zero in that case. How exactly did kas fail?

**Comment by tewarid** [comment]
It isn't kas itself that fails, but bitbake. kas does print `ERROR    - Command returned non-zero exit status 1` but does not propagate the failure.

**Comment by tewarid** [comment]
kas (I'm using version 3.1 now) is propagating bitbake error as expected. Closing issue as I don't see it now.
