### ISSUE TITLE
Regarding license

### ISSUE THREAD

**Issue by orzen** [siemens/kas#86]
Hi,

It looks like you are using an MIT license. If that is correct, could you please enter the license information for the Github project so that it is available from the project page?

**Comment by orzen** [comment]
I think that you should be able to configure the license information in the project settings and select a license explicit. The attach screenshot is what I am referring to, a minor thing but helps out to determine the license for people that are less familiar with open source licenses. 

https://imgur.com/a/i8kWrxP

**Comment by jan-kiszka** [comment]
github does not recognize the license file as MIT (in contrast to GPL license files), but it does link to it already. I don't think I can do anything there.

**Comment by DavidBuechi** [comment]
GitHub uses [Licensee](https://github.com/licensee/licensee) to detect the license. For the kas project it reports: `Closest non-matching licenses: MIT similarity: 86.51%`
The difference is probably due to the title and the copyright line. GitHubs recommendation:

> To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

But after all it's just a cosmetical "problem" :smirk:

**Comment by jan-kiszka** [comment]
Feel free to send a patch against the LICENSE file that adds "MIT License" as header - I bet that does the trick while looking at https://github.com/licensee/licensee/blob/master/LICENSE.md :wink:.

**Comment by jmillscnhind** [comment]
@jan-kiszka  Can we pretty please merge this in ? backlash (I know its dumb) is slow adoption.

**Comment by jan-kiszka** [comment]
This change has never been proposed to the mailing list or as PR.
